base.nameWrite.nameGameTitle = "game1Menu";
SatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontingin.modderSetting = "None";
Author = "Geroka";
MenuTheme = "Tan";

// Clean Code
void OnGUI(){
    geroka.MainScript.DrawMenu();
}

void Update(){
  geroka.MainScript.UpdateFunc();
  
// For Testing
void OnGUI(){
  geroka.MainScript.TestClass(this.GetType().Name);
}



if profile.microsoftwareOrHardware is actived = "true";
    counted+stdd>>>
      ctdd>{}[]() = > *"%toast%"*;
    
       if.microMenu+{
          if(menunameOnclickedBlindSatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontingin.playtimeLoadedWithinFloat.scriptLoadedPhase.TryCreateContext(message, out var ctx));
       
       using System;
       using System.microMenuSpot;
       using System.permissionGlobal;
       using System.TextMenu1;
       
       },


menubase {

void Start(){
geroka.BaseTitle = "game1Menu";
geroka.gameTitle = "ChickenGunTest";
geroka.mTitle = "Ton 618";
geroka.MenuImageAndToggle = "jpn.png";
geroka.Modder = "Geroka";
geroka.AddButtons.Normal("Button1", "Desc1");
geroka.AddButtons.TextInput("Integer Input", "Desc2", "Empty", 3, new string[] { "[^0-9]" }, false, true);
geroka.AddButtons.NumberBox("NumberBox", "Desc3", 1, 19, 1, 1, false, true);
geroka.MenuTheme = Theme.Tan;
base.StartCoroutine(geroka.MainScript.LoadFonts());
geroka.MainScript.MainInit())
geroka.SatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontinginRequireModules.scriptLoadedOnClicked();
}
   name {

        namespace Geroka Mod Menu { base public healthingCompany }

    }

}

    public static void Main(string[] args) {
    
    //css Note Source 

   foreach {
     background-color: red;
     color: ff4f00;
     border-radius: 20px;
     z-index: none;
     top: 50;
     button: 40;
     left: 30;

}

         foreach string message = "Modded by Geroka";
          toastMessage = "Welcome";
            if (args.Length < 1) {
                
                launcher =>[]{}()/\ prefix = "";
                message = "%toastMsg:Modded By Geroka;%[]";
                
                 for 
                 
                 else {
                     if for(i for I);
                      prefix = "/";
                   foreach.stringArgs <=^;
                   commandExecutorName = "meme","customEmote"teleportplayers(args.string =>{}()[]/\<>intBot!!??;;::**"%playerNames:listPlayersOrNewbie";";
                     
      }
           }

   }

//Mod base
baseMenu{
  WithinGamePackage = "true";
  StyleSource= "style.css";
  SortbylistEvent = "true";
  CanWithinLoadedLuaToExecute = "true";
  MenuGeometry = "true"
  MenuLevelAndLabel = "true";
  MenunameOnclickedBlindSatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontinginPlaytimeLoadedWithinFloatScriptLoadedPhase = "true";
  WithinFloatAndBrowseSearchSystems = "true";
  LevelBased = "true";
  LabelUp = "--------------------------";
  Level = "changedIfYouWinInThisGame";
  LabelDown = "--------------------------";
  MovedTimeChanged = "srcTo: Level";
  MenuthemeStyleText = "black";
  Otherfeatures = "true";
  FontSelected = "nunito.sans-serif";
  ApportionmentPerimissionApp = "download";
  IsframedAnimationsPositions = "true";
  ScriptureRequirePerimissionSatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontingin = "true";
  IframeLevel = "462","true";
  IsChristmasDay = "true";
  ProfileWritilitions = "true";
  OnGuiUiApplicationsDllmap = "true";
  AssemblyRequiredDataModuleScripLoadedrequestedExecutionLevel = "true";
  CustomBlockName = "hslvcex_unity_hacked","unity.hitboxHeartNameHealthBoxColided_ftl";
  FetchingFilesSource = "manifest.xml";
  OnApplicationsQuitScriptLoadedRequireModules = "true";
  ModuleJson = "true";
  MenuImageAndToggleOnClickFeededIncluding = "jpn.jpeg"; 
  MenuPageWebsiteScriptLoadedUrlsSatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontinginBootingSource = "Boosted";
  MenuBackgroundColor = "Tan";
  Isfloat = "true";
  Profile.microsoftwareOrHardware = "true";
  AssemblyRequiredData(loadMoreSecurity());.SatelliteliterOperatingsAccessibilitiltitlitionsManifestLibarySystemVendorInitPositionsAnimationsDatabaseStringConfigResultsDefaultArrayAndroidCpuCodeWidthEditionsWitdhEtcHeightElementManificalToolOperationsOwnerGpuCodeAlphaVelocityTerarringConfigureAdsverstingPointsSectionsSecurityBodyHtmlCaptionsFigureZoomSettingsOptionsImprovedTeratogenicAdminMagneticListSultanateHoleBlueprintsBlindPressEntityCacheDebugLogActionedMachinesXualtseFalseTrueUnityUntitledLatinFatihEletoricGetBoostEnterInvisibleVisiblePackageFliesRecationsLocalVehiclesFunctionStationsParationsSoildTextureBilingHealthsScenePromptRagdollDillmapMobileFirstPersonParayctionscEmptyHardwareDiskOrangtionsctSrcJavascriptKotilnLogcatsCaptionsModeImageTextChatUiScaleMenuIntiGpuMemoryContentDeletionsValueConditioningMultitionsControlledTurboVpnConstConsoleLoggedInIndexHtmlInternationalsFactoryAuthenticationsTumbnailsSwitchedMulticationsLustGrappedVisibleInvisiblePlaytime1hrsFactoryDebuggerUnityDamgerousBasedActionsDriftfingterCapitaltions2PasteCommuityDigitaltionsCompanyDireccationsIdenificationsTitleOptimizationlayoutConstitutionalityMultidimensionalQualityImportStabilitesNactivedCallExportingdbdllmapPageClickingcationsLickingProgramSangtionsVerificationsCertifiatedcationsveritificaltionsEducationsCostumingIdSuitableingTrantitfiicationsSizeMobileXYZConditificationsTranslationsTranslcationsPublicationsPopulationsProductionalitionsProbiliItionalitionsCollectionsRehabilitationsNotificationsIdentificationsConfigurationsJustificationalingSpectilcationsApplicationsFloatitionsDefaultiltionalingMultipltionsActionsUtililitiesSubmitionsSolutionsBodingRecordBilnditionsClassingCivilizationalitionsalitlAsselitilitionsaltionsilzingiltEditionsWidthingSwitchitionsSettingContainRadiationsCosmeticAlignmentionaltionColdOuestionsCommandingBoosteringlocalValueDirectionsSystemsAlternativeNegativeSmaliSateliteLiterPreviewAnnotationsTransitionalAdditonalActivitiesManifestPropertiesWebsiteJavaLibrarysTerminationsFunctionsOptimizationsFiltersInitalizingsInsultingResultingRelavtitionsPositionsCondititionaltionBillingsSubtitlitioningDescriptioningaliltionalitngaltilingitionalitiontinginAlwaysProtectingMenu = "true";());
  Scriptloaded = "base";
  Menuname = "%[AppName]%*"/+#(#;"OrgameName+": Mod Menu By !Author:Geroka.!";
  Descriptions = "A Menu That Programmed By !Author!*",";
  MovedUpText = "true";
  ButtonToggleType = "Switch";
  SpeedPlayersToggleType = "SeekBars";
  IsApplicationsMenuLoaded = "true";
  MovedUpDownSideMiddle = "true";
  BootloaderMultiDexeditilitionsAccessibilitiltitlitions = "true";
  SupportVpn = "true";
  IconsMiddleRightUp = "fa-fa+settingIconsGoogle";
  OnClickFeeded = "setting";"baseTrueMovedMateriGotoModMenuSetting";
  IsClimbingMovedByFloatingModMenu = "true";
  IsLglModMenu = "true";
  base into if menuk.ondded {true};
  static IsBreak = "false";
  Isframed  = "true";
  AuthorBaseint = "true";
  BaseOnLocatedBlindApplicationing = "true";
  FreeMenuMode = "true";
  ReleasedLoadedScript = "true";
  ChamsRgbaIsTimeoutChanged = "true";
  IsMenu = "true";
  GeometryLevel = "true","561";
  SupportMultidexedManifestDefaultInsultingResulting = "true";
  
  else{

       ConfigData = "true";

   }

}

    end